
[project]
authors = [{ name = "Igor Passchier", email = "igor.passchier@gmail.com" }]
name = "phototag"
version = "0.1.0"
requires-python = ">=3.14,<4.0"
classifiers = [
  "License :: MIT ",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
]
dependencies = [
  "matplotlib",
  "Pillow",
  "py3exiv2",
  "pydantic~=2.13",
  "python-dotenv",
  "requests",
  "sortedcontainers",
  "tinydb",
  "uvicorn (>=0.49.0,<0.50.0)",
  "fastapi (>=0.138.2,<0.139.0)",
]
description = "Igors photo tagging library"
# dynamic = ["version"]
license = { text = "MIT" }

[project.urls]
#"Bug Tracker" = "https://Z003KBKV@dev.azure.com/Z003KBKV/Simulytic/_git/psimclient"
#Homepage = "https://Z003KBKV@dev.azure.com/Z003KBKV/Simulytic/_git/psimclient"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project.scripts]
phototag = "phototag.cli:main"
exif = "phototag.exif:main"

[project.optional-dependencies]

linting = ["black~=26.0", "sortedcontainers-stubs", "types-requests~=2.32"]

[tool.pytest.ini_options]
addopts = "--cov --cov-report=term-missing"
testpaths = ["test"]

[tool.coverage.run]
branch = true
source = ["src"]
omit = ["*/__init__.py", "*/main.py"]

[tool.coverage.report]
exclude_lines = [
  "pragma: no cover",
  "def __repr__",
  "raise AssertionError",
  "raise NotImplementedError",
  "if __name__ :",
]
show_missing = true
fail_under = 0

[tool.black]
line-length = 120

[tool.mypy]
exclude = 'venv|site-packages|.vscode|build|test'
ignore_missing_imports = true
plugins = ["tinydb.mypy_plugin"]

[tool.tox]
legacy_tox_ini = """
    [tox]
    min_version = 4.0
    env_list =
        py314
        black
        mypy

    [testenv]
    allowlist_externals = poetry
    commands_pre = poetry install --no-root --sync --all-groups
    commands = poetry run pytest -v test --import-mode importlib


    [testenv:black]
    allowlist_externals = poetry
    commands_pre = poetry install --no-root --sync --all-groups
    commands = poetry run black --check --diff src


    [testenv:mypy]
    allowlist_externals = poetry
    commands_pre = poetry install --no-root --sync --all-groups
    commands = poetry run mypy src
"""

[dependency-groups]
dev = [
  "black~=26.0",
  "build~=1.0",
  "isort~=8.0",
  "jupyter~=1.1",
  "nbqa~=1.9",
  "sortedcontainers-stubs",
  "types-requests~=2.32",
]

testing = [
  "jupyter~=1.1",
  "nbqa~=1.9",
  "pydantic~=2.13",
  "pytest_cov~=4.1",
  "pytest-mock~=3.14",
  "pytest~=7.2",
  "sortedcontainers-stubs",
  "tox~=4.0",
]
