[project]
name = "phototagging"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Igor Passchier", email = "igor.passchier@gmail.com" }]
requires-python = ">=3.14,<4.0"
dependencies = [
    "fastapi~=0.138",
    "matplotlib>=3.11.0",
    "pillow>=12.2.0",
    "py3exiv2>=0.12.0",
    "pydantic~=2.13",
    "python-dotenv>=1.2.2",
    "requests~=2.33",
    "sortedcontainers>=2.4.0",
    "tinydb>=4.8.2",
    "uvicorn~=0.49",
]
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Private :: Do Not Upload",
]


[project.scripts]
phototagging = "phototagging.cli:main"
exif = "phototagging.exif:main"


[build-system]
requires = ["uv_build>=0.11.22,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    { include-group = "lint" },
    { include-group = "test" },
    "jupyter>=1.1.1",
    "mypy>=2.1.0",
    "nbqa>=1.9.1",
    "sortedcontainers-stubs>=2.4.3",
    "types-requests~=2.33",
]

lint = ["ruff>=0.15.20"]

test = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "pytest-mock>=3.15.1",
    "tox>=4.56.1",
]
