[project]
name = "backend"
version = "0.1.0"
description = ""
authors = [
    {name = "Igor Passchier",email = "igor.passchier@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14,<4.0"
dependencies = [
    "fastapi (==0.115.7)",
    "uvicorn (==0.34.0)",
    "phototag @ file:///Users/igor/Development/Personal/phototagging",
    "sortedcontainers (>=2.4.0,<3.0.0)",
    "sortedcontainers-stubs (>=2.4.3,<3.0.0)"]

[tool.poetry]
packages = [{include = "app", from = "src"}]

[tool.poetry.dependencies]
phototag = {develop = true}
[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
